main: me.syncwrld.minecraft.pingcompass.PingCompassPlugin
name: PingCompass
version: 1.0.0
api-version: 1.21

author: syncwrld
website: https://github.com/syncwrld/ping-compass

commands:
  givepc:
    permission: "pingcompass.give"
    description: "Gives the ping compass to a certain player"
    aliases:
      - givepingcompass
      - pingcompassgive
      - pcgive